fix: changes trivia to interview question in all learn folders
FrontendFreaks/Official-Website pull request #84
Opened 2023-10-02 06:02 UTC by Hrithik0112

## Fixes Issue
- Fixes #59 #49 

## Changes

changes "trivia" name to "Interview Question" in All "Learn" folder i.e. Html basic ,CSS basic , CSS flex , CSS gird.

## Changes proposed

## Check List (Check all the applicable boxes) 

- [x] My code follows the code style of this project.
- [x] My change requires changes to the documentation.
- [x] I have updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] This PR does not contain plagiarized content.
- [x] The title of my pull request is a short description of the requested changes.

## Screenshots

![Screenshot 2023-10-02 112205](https://github.com/FrontendFreaks/Official-Website/assets/122002784/63d17342-a181-470c-9ce5-bc7fdc8aa5ec)

![Screenshot 2023-10-02 112137](https://github.com/FrontendFreaks/Official-Website/assets/122002784/ae947adc-13af-4e13-973a-2c2a536a7f2d)
![Screenshot 2023-10-02 112217](https://github.com/Front
![Screenshot 2023-10-02 112229](https://github.com/FrontendFreaks/Official-Website/assets/122002784/5019305f-6ca2-4068-a6a0-81b673715e1e)
endFreaks/Official-Website/assets/122002784/e4621dc9-9c3e-4da8-9d49-687a8c840c48)

2023-10-02 07:23 UTC, Vishal-raj-1 commented on content/batch/learn/css/flex.mdx
> +
remove extra line

2023-10-02 07:23 UTC, Vishal-raj-1 commented on content/batch/learn/css/flex.mdx
> +
remove extra line

2023-10-02 07:23 UTC, Vishal-raj-1 commented on content/batch/learn/css/grid.mdx
> +    Interview Questions on css grid
it should be "CSS Grid"

2023-10-02 07:23 UTC, Vishal-raj-1 commented on content/batch/learn/html/basic.mdx
> +    Interview Questions on html
it should be "HTML"

2023-10-02 07:24 UTC, Vishal-raj-1 commented on content/batch/learn/html/basic.mdx
> +
remove extra line

2023-10-02 07:24 UTC, Vishal-raj-1 commented on content/batch/learn/css/grid.mdx
> +
remove extra line

2023-10-02 07:24 UTC, Vishal-raj-1 commented on content/batch/learn/css/basic.mdx
> +    Interview Questions on css
it should be "CSS"

2023-10-02 07:24 UTC, Vishal-raj-1 requested changes
fix all changes

2023-10-02 18:33 UTC, Hrithik0112 commented
Understood.

2023-10-03 03:06 UTC, Hrithik0112 commented
@Vishal-raj-1 done as you told. is there anything to improve ?

2023-10-03 05:00 UTC, merged